services:
  blueboard:
    build:
      dockerfile: docker/Dockerfile.blueboard-dev
    ports:
      - 5279:5279
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Database=BlueboardDb;Username=postgres;Password=postgres
    volumes:
      - ./Blueboard:/app/Blueboard
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
